import type { Case, TimelineEntry, Transaction, Evidence } from "@/types/database";

export async function exportZip(
  caseData: Case,
  timeline: TimelineEntry[],
  transactions: Transaction[],
  evidence: Evidence[]
): Promise<void> {
  const [{ default: JSZip }, { exportCsvString }] = await Promise.all([
    import("jszip"),
    import("@/lib/exportCsv"),
  ]);

  const zip = new JSZip();

  const manifest = [
    `Scam Dam Evidence Bundle`,
    `Case: ${caseData.title}`,
    `Generated: ${new Date().toISOString()}`,
    `Scam Type: ${caseData.scam_type}`,
    `Total Lost: ${caseData.total_lost} ${caseData.currency}`,
    ``,
    `Files included:`,
    `- manifest.txt (this file)`,
    `- transactions.csv`,
    `- evidence-index.txt`,
    `- timeline.txt`,
    `- ${evidence.length} evidence file(s)`,
    ``,
    `Reporting Agencies:`,
    `- FBI IC3: https://www.ic3.gov`,
    `- FTC: https://reportfraud.ftc.gov`,
    `- CFPB: https://www.consumerfinance.gov/complaint/`,
    ``,
    `⚠️ Not legal advice. This bundle was generated by Scam Dam.`,
  ].join("\n");

  zip.file("manifest.txt", manifest);

  const csvContent = exportCsvString(caseData, transactions);
  zip.file("transactions.csv", csvContent);

  const evidenceIndex = [
    "Evidence Index",
    "=".repeat(50),
    ...evidence.map(
      (ev, i) =>
        `${i + 1}. ${ev.file_name} (${ev.category}) - ${(ev.file_size / 1024).toFixed(1)} KB${ev.description ? " - " + ev.description : ""}`
    ),
  ].join("\n");
  zip.file("evidence-index.txt", evidenceIndex);

  const timelineContent = [
    "Timeline of Events",
    "=".repeat(50),
    ...[...timeline]
      .sort((a, b) => new Date(a.event_date).getTime() - new Date(b.event_date).getTime())
      .map((e) => `${e.event_date} | ${e.event_type.replace(/_/g, " ").toUpperCase()} | ${e.description}`),
  ].join("\n");
  zip.file("timeline.txt", timelineContent);

  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `scam-evidence-${caseData.title.replace(/[^a-z0-9]/gi, "-").toLowerCase()}.zip`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
