import type { Case, TimelineEntry, Transaction, Evidence } from "@/types/database";
import { formatCurrency, formatDate } from "@/lib/utils";

const scamTypeLabels: Record<Case["scam_type"], string> = {
  task_scam: "Task Scam",
  crypto_investment: "Crypto Investment Scam",
  fake_job: "Fake Job Offer Scam",
  romance_scam: "Romance Scam",
  other: "Other Scam",
};

export async function generateReport(
  caseData: Case,
  timeline: TimelineEntry[],
  transactions: Transaction[],
  evidence: Evidence[]
): Promise<void> {
  const { default: jsPDF } = await import("jspdf");
  const { autoTable } = await import("jspdf-autotable");

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentW = pageW - margin * 2;

  const addFooter = () => {
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(
        "⚠️ This document was generated to assist with reporting. It is not legal advice.",
        margin,
        pageH - 8,
        { maxWidth: contentW - 20 }
      );
      doc.text(`Page ${i} of ${pageCount}`, pageW - margin, pageH - 8, { align: "right" });
    }
  };

  // Cover page
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageW, pageH, "F");
  doc.setFontSize(28);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text("Scam Evidence Report", pageW / 2, 60, { align: "center" });

  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(203, 213, 225);
  doc.text(caseData.title, pageW / 2, 80, { align: "center", maxWidth: contentW });

  doc.setFontSize(11);
  doc.setTextColor(156, 163, 175);
  doc.text(scamTypeLabels[caseData.scam_type], pageW / 2, 95, { align: "center" });

  doc.setFontSize(20);
  doc.setTextColor(239, 68, 68);
  doc.setFont("helvetica", "bold");
  doc.text(formatCurrency(caseData.total_lost, caseData.currency) + " lost", pageW / 2, 115, { align: "center" });

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 116, 139);
  doc.text(
    `Generated: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
    pageW / 2,
    130,
    { align: "center" }
  );

  doc.setFontSize(9);
  doc.setTextColor(75, 85, 99);
  doc.text(
    "This document was generated by Scam Dam to assist with evidence organization.",
    pageW / 2,
    pageH - 20,
    { align: "center" }
  );
  doc.text("It is not legal advice.", pageW / 2, pageH - 14, { align: "center" });

  // Case Summary page
  doc.addPage();
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, pageW, pageH, "F");

  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(17, 24, 39);
  doc.text("Case Summary", margin, margin + 10);

  autoTable(doc, {
    startY: margin + 20,
    body: [
      ["Case Title", caseData.title],
      ["Scam Type", scamTypeLabels[caseData.scam_type]],
      ["Status", caseData.status.charAt(0).toUpperCase() + caseData.status.slice(1)],
      ["Total Lost", formatCurrency(caseData.total_lost, caseData.currency)],
      ["Case Opened", formatDate(caseData.created_at)],
      ["Description", caseData.description ?? "—"],
    ],
    theme: "plain",
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 45, textColor: [75, 85, 99] },
      1: { textColor: [17, 24, 39] },
    },
    styles: { fontSize: 10, cellPadding: 3 },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    margin: { left: margin, right: margin },
  });

  // Timeline
  if (timeline.length > 0) {
    const sortedTimeline = [...timeline].sort(
      (a, b) => new Date(a.event_date).getTime() - new Date(b.event_date).getTime()
    );

    doc.addPage();
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(17, 24, 39);
    doc.text(`Timeline of Events (${sortedTimeline.length})`, margin, margin + 10);

    autoTable(doc, {
      startY: margin + 20,
      head: [["Date", "Event Type", "Description"]],
      body: sortedTimeline.map((e) => [
        formatDate(e.event_date),
        e.event_type.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
        e.description,
      ]),
      theme: "striped",
      headStyles: { fillColor: [220, 38, 38], textColor: 255, fontStyle: "bold" },
      styles: { fontSize: 9, cellPadding: 3 },
      columnStyles: { 0: { cellWidth: 28 }, 1: { cellWidth: 38 } },
      margin: { left: margin, right: margin },
    });
  }

  // Transactions
  if (transactions.length > 0) {
    const sortedTx = [...transactions].sort(
      (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()
    );
    const totalLost = sortedTx
      .filter((t) => t.transaction_type === "deposit" || t.transaction_type === "fee")
      .reduce((acc, t) => acc + t.amount, 0);

    doc.addPage();
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(17, 24, 39);
    doc.text(`Transactions (${sortedTx.length})`, margin, margin + 10);

    autoTable(doc, {
      startY: margin + 20,
      head: [["Date", "Type", "Amount", "Platform", "Wallet / Exchange"]],
      body: [
        ...sortedTx.map((t) => [
          formatDate(t.date),
          t.transaction_type.charAt(0).toUpperCase() + t.transaction_type.slice(1),
          formatCurrency(t.amount, t.currency),
          t.platform,
          t.wallet_address ?? t.exchange ?? "—",
        ]),
        ["", "TOTAL LOST", formatCurrency(totalLost, sortedTx[0]?.currency ?? "USD"), "", ""],
      ],
      theme: "striped",
      headStyles: { fillColor: [220, 38, 38], textColor: 255, fontStyle: "bold" },
      styles: { fontSize: 9, cellPadding: 3 },
      columnStyles: { 0: { cellWidth: 25 }, 1: { cellWidth: 22 }, 2: { cellWidth: 28 } },
      margin: { left: margin, right: margin },
    });

    // Wallet addresses list
    const wallets = sortedTx
      .filter((t) => t.wallet_address)
      .map((t) => t.wallet_address as string);
    if (wallets.length > 0) {
      // jspdf-autotable stores the last table result on the doc instance
      type DocWithAutoTable = typeof doc & { lastAutoTable?: { finalY?: number } };
      const lastY = (doc as DocWithAutoTable).lastAutoTable?.finalY ?? margin + 80;
      doc.setFontSize(13);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(17, 24, 39);
      doc.text("Wallet Addresses", margin, lastY + 15);
      doc.setFont("courier", "normal");
      doc.setFontSize(9);
      doc.setTextColor(55, 65, 81);
      wallets.forEach((w, i) => {
        doc.text(`${i + 1}. ${w}`, margin, lastY + 25 + i * 8, { maxWidth: contentW });
      });
    }
  }

  // Evidence index
  if (evidence.length > 0) {
    doc.addPage();
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(17, 24, 39);
    doc.text(`Evidence Index (${evidence.length} files)`, margin, margin + 10);

    autoTable(doc, {
      startY: margin + 20,
      head: [["#", "File Name", "Category", "Size", "Description"]],
      body: evidence.map((ev, i) => [
        String(i + 1),
        ev.file_name,
        ev.category.replace("_", " ").replace(/\b\w/g, (c) => c.toUpperCase()),
        `${(ev.file_size / 1024).toFixed(1)} KB`,
        ev.description ?? "—",
      ]),
      theme: "striped",
      headStyles: { fillColor: [220, 38, 38], textColor: 255, fontStyle: "bold" },
      styles: { fontSize: 9, cellPadding: 3 },
      columnStyles: { 0: { cellWidth: 10 }, 2: { cellWidth: 24 }, 3: { cellWidth: 18 } },
      margin: { left: margin, right: margin },
    });
  }

  // Reporting agencies
  doc.addPage();
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(17, 24, 39);
  doc.text("Reporting Agencies", margin, margin + 10);

  const agencies = [
    ["FBI Internet Crime Complaint Center (IC3)", "https://www.ic3.gov", "Primary federal agency for cybercrime and internet fraud reports."],
    ["FTC Report Fraud", "https://reportfraud.ftc.gov", "Federal Trade Commission consumer fraud reporting portal."],
    ["CFPB Consumer Complaint", "https://www.consumerfinance.gov/complaint/", "File complaints against banks, lenders, and financial institutions."],
    ["CISA Report", "https://www.cisa.gov/report", "Cybersecurity and Infrastructure Security Agency."],
  ];

  autoTable(doc, {
    startY: margin + 20,
    head: [["Agency", "URL", "Notes"]],
    body: agencies,
    theme: "striped",
    headStyles: { fillColor: [220, 38, 38], textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 9, cellPadding: 3 },
    columnStyles: { 0: { cellWidth: 55 }, 1: { cellWidth: 65 } },
    margin: { left: margin, right: margin },
  });

  addFooter();

  const fileName = `scam-evidence-${caseData.title.replace(/[^a-z0-9]/gi, "-").toLowerCase()}.pdf`;
  doc.save(fileName);
}
